### ISSUE TITLE
Anyway to bring in colour output?

### ISSUE THREAD

**Issue by JikkuJose** [hawx/guard-shell#22]
It seems all colours are stripped off from the output when using this plugin. Is there a way to bring in colour?

**Comment by pghalliday** [comment]
+1

**Comment by kangkyu** [comment]
+1

**Comment by hawx** [comment]
Feel free to send a pull request, but I'm not really maintaining this anymore.

**Comment by kangkyu** [comment]
I found `--pride` option minitest didn't work with guard-shell, but color of minitest-reporters still showed! Now I use guard-shell like this:
```rb
guard :shell do
  watch(/^(.+)\.rb$/) do |m|
    `ruby -I"lib:test" -r"./test_helper" #{m[1].chomp('_test')}_test.rb`
  end
end
``` 
(I have test_helper.rb with `require "minitest/reporters"` et cetera setting) I wish to send a pull request by the way, after investigating all the code, but in the future :wink:
